# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 23:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=144)),
                ('illustration', models.URLField(max_length=500)),
                ('trusted', models.BooleanField(default=False)),
                ('secret', models.CharField(default=uuid.uuid4, editable=False, max_length=32)),
                ('set_token_url', models.CharField(help_text='eg: http://localhost:8008/auth/set-token/', max_length=5000)),
                ('callback_url', models.CharField(help_text='eg: http://localhost:8008/auth/callback/', max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'applications',
                'verbose_name': 'application',
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_has_authorized', models.BooleanField(default=False)),
                ('token', models.CharField(default=uuid.uuid4, max_length=32)),
                ('last_token_refresh', models.DateTimeField(default=datetime.datetime.now)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_network_provider.App')),
            ],
            options={
                'verbose_name_plural': 'credentials',
                'verbose_name': 'credential',
            },
        ),
        migrations.CreateModel(
            name='NetworkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('last_verification', models.DateTimeField(default=datetime.datetime.now)),
                ('apps', models.ManyToManyField(through='auth_network_provider.Credentials', to='auth_network_provider.App')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'membres du réseau',
                'verbose_name': 'membre du réseau',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='credentials',
            name='network_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_network_provider.NetworkUser'),
        ),
    ]
