# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='user_has_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
