# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkApp',
            new_name='App',
        ),
    ]
