# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
