# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0002_auto_20161226_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='Une super appli !', max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='illustration',
            field=models.URLField(default='localhost:8008/static/favicon.png', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='networkuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
