# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-24 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0002_credentials_user_has_authorized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'credential', 'verbose_name_plural': 'credentials'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='An Onymous', max_length=255, verbose_name='Prénom et Nom'),
            preserve_default=False,
        ),
    ]
