# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0003_auto_20160708_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
