# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0005_auto_20161215_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
