# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0006_auto_20161215_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
