# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0007_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='callback_url',
            field=models.CharField(help_text='http://localhost:8008/callback/', max_length=5000),
        ),
        migrations.AlterField(
            model_name='app',
            name='set_token_url',
            field=models.CharField(help_text='http://localhost:8008/set-token/', max_length=5000),
        ),
    ]
