# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network_provider', '0005_auto_20160724_2230'),
        ('auth_network_provider', '0008_auto_20161215_1929'),
    ]

    operations = [
    ]
